# Generated by Django 5.0.4 on 2024-04-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_publish_on_blog_created_on_blog_updated_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
